name: CI
on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.x
      - name: pip install
        run: |
          pip install -r requirements.txt
      - name: Build
        run: |
          python ./src/main.py
      - name: Commit change & Push
        run: |
          git config user.name 'github-actions[bot]'
          git config user.email 'github-actions[bot]@users.noreply.github.com'
          git commit -am "bot: update results automatically"
          git push
