name: Draw
on:
  workflow_dispatch:
jobs:
  build:
    if: github.repository == 'MHuiG/zeta-zero'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.x
      - name: pip install
        run: |
          pip install -r requirements.txt
      - name: Build
        run: |
          python src/draw.py
      - name: Commit change & Push
        run: |
          git config user.name 'github-actions[bot]'
          git config user.email '41898282+github-actions[bot]@users.noreply.github.com'
          git add .
          git commit -am "bot: update results automatically"
          git push
